version: "3.7"

services:
  db:
    image: postgres
    container_name: rentalx_db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=rentalx
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: rentalx
    depends_on:
      - db
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app

volumes:
  pgdata:
